import { Sport, League } from "./types";

export const eventsData = [
  // NBA Events
  {
    id: 1,
    event: "Lakers vs. Celtics",
    currentOdds: 1.8,
    changePercent: 2,
    volume: 15000,
    supply: 50000,
    sport: Sport.Basketball,
    league: League.NBA,
  },
  {
    id: 2,
    event: "Warriors vs. Nets",
    currentOdds: 1.6,
    changePercent: -1,
    volume: 20000,
    supply: 60000,
    sport: Sport.Basketball,
    league: League.NBA,
  },
  {
    id: 3,
    event: "Bucks vs. Suns",
    currentOdds: 2.2,
    changePercent: 3,
    volume: 18000,
    supply: 55000,
    sport: Sport.Basketball,
    league: League.NBA,
  },

  // EPL Events
  {
    id: 4,
    event: "Arsenal vs. Chelsea",
    currentOdds: 1.7,
    changePercent: 1.5,
    volume: 25000,
    supply: 70000,
    sport: Sport.Soccer,
    league: League.EPL,
  },
  {
    id: 5,
    event: "Manchester United vs. Liverpool",
    currentOdds: 2.0,
    changePercent: -2,
    volume: 30000,
    supply: 80000,
    sport: Sport.Soccer,
    league: League.EPL,
  },
  {
    id: 6,
    event: "Manchester City vs. Tottenham",
    currentOdds: 1.5,
    changePercent: 2.5,
    volume: 22000,
    supply: 65000,
    sport: Sport.Soccer,
    league: League.EPL,
  },

  // NHL Events
  {
    id: 7,
    event: "Maple Leafs vs. Canadiens",
    currentOdds: 1.9,
    changePercent: 0,
    volume: 17000,
    supply: 60000,
    sport: Sport.Hockey,
    league: League.NHL,
  },
  {
    id: 8,
    event: "Rangers vs. Bruins",
    currentOdds: 2.1,
    changePercent: -1.5,
    volume: 16000,
    supply: 58000,
    sport: Sport.Hockey,
    league: League.NHL,
  },
  {
    id: 9,
    event: "Blackhawks vs. Red Wings",
    currentOdds: 2.3,
    changePercent: 3.5,
    volume: 14000,
    supply: 53000,
    sport: Sport.Hockey,
    league: League.NHL,
  },
  {
    id: 10,
    event: "Golden Knights vs. Avalanche",
    currentOdds: 1.8,
    changePercent: 2,
    volume: 19000,
    supply: 61000,
    sport: Sport.Hockey,
    league: League.NHL,
  },
];
