export const soccerData = [
  {
    id: 1,
    homeTeam: "Manchester United",
    awayTeam: "Liverpool",
    location: "Manchester, Old Trafford",
    date: new Date("2024-04-01T15:00:00"),
    league: "Premier League",
  },
  {
    id: 2,
    homeTeam: "Real Madrid",
    awayTeam: "FC Barcelona",
    location: "Madrid, Santiago Bernabéu Stadium",
    date: new Date("2024-04-02T19:00:00"),
    league: "La Liga",
  },
  {
    id: 3,
    homeTeam: "Bayern Munich",
    awayTeam: "Borussia Dortmund",
    location: "Munich, Allianz Arena",
    date: new Date("2024-04-03T20:00:00"),
    league: "Bundesliga",
  },
  {
    id: 4,
    homeTeam: "AC Milan",
    awayTeam: "Inter Milan",
    location: "Milan, San Siro",
    date: new Date("2024-04-04T18:30:00"),
    league: "Serie A",
  },
  {
    id: 5,
    homeTeam: "Paris Saint-Germain",
    awayTeam: "Olympique Marseille",
    location: "Paris, Parc des Princes",
    date: new Date("2024-04-05T21:00:00"),
    league: "Ligue 1",
  },
  {
    id: 6,
    homeTeam: "Chelsea",
    awayTeam: "Arsenal",
    location: "London, Stamford Bridge",
    date: new Date("2024-04-06T16:00:00"),
    league: "Premier League",
  },
  {
    id: 7,
    homeTeam: "Juventus",
    awayTeam: "Napoli",
    location: "Turin, Juventus Stadium",
    date: new Date("2024-04-07T20:45:00"),
    league: "Serie A",
  },
  {
    id: 8,
    homeTeam: "Atletico Madrid",
    awayTeam: "Valencia",
    location: "Madrid, Wanda Metropolitano",
    date: new Date("2024-04-08T19:00:00"),
    league: "La Liga",
  },
];
